### ISSUE TITLE
Various patterns questions on Binary Trees and Binary Search Tree

### ISSUE THREAD

**Issue by Bayesian4042** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#101]
Hey @Joshitha18 , I'm Abhilasha, a GSSoC 2021 participant.

I would like to work and add different pattern questions based on binary tree and binary search tree using Python.

Please let me know if I can work on it. Thanks :)

**Comment by Joshitha18** [comment]
@Bayesian4042 mention the questions u want to add

**Comment by Bayesian4042** [comment]
**Binary Tree:**

1. tree traversal - inorder, preorder, postorder, level order
2. depth of binary tree
3. diameter of binary tree
4. path sum
5. horizontal distances in binary tree.

**Binary Search Tree**
1. validate binary tree
2. LCA in BST
3. Inorder successor in BST

Let me know @Joshitha18 if this is valid questions to contribute. thanks :)

**Comment by rashrey2308** [comment]
@Bayesian4042 I would suggest you to create different issues for every question that you want to add.
