### ISSUE TITLE
MAX SUM OF CONTIGUOUS SUBARRAY.

### ISSUE THREAD

**Issue by mu593** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#105]
I am GSSOC'2021 participant
Please assign me this issue.
I want to add code of one of most renown question.

this question is implementation of kadane's algorithm

**Comment by rcoder23** [comment]
@mu593 You can work on it.

**Comment by rcoder23** [comment]
Closing due to inactive
