### ISSUE TITLE
Add Factorial Trailing Zeroes Problem Under Numerical Folder.

### ISSUE THREAD

**Issue by NEERAJAP2001** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#111]
Problem statement:  Given an integer n, return the number of trailing zeroes in n!

This problem would be implemented into this [this](https://github.com/Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo/tree/main/Numerical) folder.

I'd Like to work on this issue as a part of the GSSOC-21

**Comment by rcoder23** [comment]
@NEERAJAP2001 You can work on it
