### ISSUE TITLE
All major Algorithms in python

### ISSUE THREAD

**Issue by robin025** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#12]
hey i am GSSoC 21 participant and would like to add major algorithms in python with all required documentation so i would like to work on this feature/issue

I will be adding Greedy Algorithms, backtracking, Dynamic Programming, and all remaining data structures in class based components

looking forward to your reply
thank you

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.
