### ISSUE TITLE
Check if a number is neon number or not under Numerical section

### ISSUE THREAD

**Issue by ankan1811** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#122]
A neon number is a number where the sum of digits of square of the number is equal to the number. The task is to check a neon number.

Input : 9
Output : Neon Number
Explanation: square is 9*9 = 81 and 
sum of the digits of the square is 9.

**Comment by ankan1811** [comment]
Please assign it to me uder GSSoC'21. @Joshitha18

**Comment by rcoder23** [comment]
@ankan1811 are you still working . ??

**Comment by rcoder23** [comment]
Close due to inactive

**Comment by ankan1811** [comment]
@rcoder23  why did you close this?
I am still working!!!
It is only 2 days...People in other projects take more than a week to solve the issue!!!
