### ISSUE TITLE
Array Solution 

### ISSUE THREAD

**Issue by divyanshu887** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#124]
I want to work on writing solution of array question in python 
can u assign me ? @Joshitha18 @rcoder23

**Comment by Joshitha18** [comment]
@divyanshu887 mention the questions

**Comment by divyanshu887** [comment]
1-find the Median of 2 sorted arrays of equal size
2-find the Median of 2 sorted arrays of different size
3-find the Minimum no. of operations required to make an array palindrome

i would like to add solution of above problems in Topic Wise Questions with Solutions/Array.
@Joshitha18

**Comment by Joshitha18** [comment]
@divyanshu887 do you mean min number of merge operations in Q3?

**Comment by divyanshu887** [comment]
yes @Joshitha18
