### ISSUE TITLE
ATM code

### ISSUE THREAD

**Issue by srisatya1197** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#128]
I want to add ATM code in codechef it's a beginner code .My code is simple to understand . I'm a participant of GSSOC'21 please assign me this work.

**Comment by Joshitha18** [comment]
@srisatya1197 u can work on it. Add it in respective topic with readme file explaining question and example inputs

**Comment by srisatya1197** [comment]
Sure ma'am

**Comment by rcoder23** [comment]
@srisatya1197 Are You still working on it.?

**Comment by srisatya1197** [comment]
Due to assignments and college exams I didn't start but I'll submit it by tomorrow night

**Comment by rcoder23** [comment]
@srisatya1197 I understand.  All the best for exams

**Comment by srisatya1197** [comment]
Thank you Sir

**Comment by srisatya1197** [comment]
@rcoder23 Sir How do I add readme file

**Comment by srisatya1197** [comment]
@Joshitha18 ma'am could you please explain me how to add readme file . I only know to add code . Should I describe the question in my code as comment with sample test cases

**Comment by rcoder23** [comment]
> @Joshitha18 ma'am could you please explain me how to add readme file . I only know to add code . Should I describe the question in my code as comment with sample test cases

Yes ! Describe question in code as comment with simple test cases.

**Comment by srisatya1197** [comment]
@rcoder23 I made a pr please review it

**Comment by rcoder23** [comment]
@srisatya1197 mention pull request no.

**Comment by rcoder23** [comment]
@srisatya1197 #194 code is correct . create new pull request only for ATM code and add ATM code soution in Topic Wise Questions with Solutions folder .

**Comment by srisatya1197** [comment]
@rcoder23 Sir  I made a folder (Codechef) and then I made another directory i.e. (beginner) init I added the ATM code Sir

**Comment by srisatya1197** [comment]
@rcoder23 Sir in topic wise questions folder I should add codechef folder in it should I add beginner folder or should I directly enter the code.

**Comment by srisatya1197** [comment]
@rcoder23 Sir may I know why in the world it's showing the issue, the issue must be closed after merging into the repo right?
