### ISSUE TITLE
Data Structures in Python

### ISSUE THREAD

**Issue by Sheetal777** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#13]
Hello, I am a GSSoC'21 participant and would like to add few Python Scripts for Data Structures like Circular Linked list, Arrays/Lists, Queue, etc.

The codes will be well commented and a description would be added about what it basically does. 

Looking forward to add more scripts in the repo.

**Comment by Dhanush2612** [comment]
Hi I am participant at GSSOC 2021. Can you assign me this issue?

**Comment by kashika0112** [comment]
I'm a GSSOC'21 Participant and would like to contribute to this issue specifically by adding questions related to arrays and sorting. I hope this issue could be assigned to me!

**Comment by rcoder23** [comment]
Project mentor @i-tick .please add label gssoc21 in this issues .

**Comment by sayantani11** [comment]
Hi I would like to work on this issue can you please assign me this for GSSoC'21?

**Comment by prathimacode-hub** [comment]
Hey, I'm a GSSOC21 participant. I would like to work on this issue. Can you assign it to me?

**Comment by Ritu01-git** [comment]
Hey ,I am GSSOC participant,  I would like to work on this issue , can you please assign it to me?
