### ISSUE TITLE
Add BFS and DFS Traversal Algorithms

### ISSUE THREAD

**Issue by muthuannamalai12** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#133]
Graphs are a powerful and versatile data structure that easily allows you to represent real-life relationships between different types of data (nodes). Graphs are one of the most difficult topics of data structure.
I would love to work on Breadth-First Search (BFS) and Depth-First Search (DFS) Graph traversal algorithms.

**Comment by muthuannamalai12** [comment]
@Joshitha18 Please assign me this under GSSOC '21.

**Comment by muthuannamalai12** [comment]
@Joshitha18 Please assign me this under GSSOC '21.

**Comment by muthuannamalai12** [comment]
@Joshitha18 Please assign me this under GSSOC '21.

**Comment by muthuannamalai12** [comment]
@Joshitha18 Please assign me this under GSSOC '21.

**Comment by Ananya9878** [comment]
Please assign this to me.

**Comment by rashrey2308** [comment]
Kindly be specific with the codes that you wish to add. Graph traversals is a very generic description.

**Comment by muthuannamalai12** [comment]
@rashrey2308 Is it okay now??

**Comment by rashrey2308** [comment]
@muthuannamalai12 BFS has already been implemented and a pull request regarding the code for DFS has already been made. Kindly check for some other algorithm which is not present and create an issue for the same. Closing this issue as of now.
