### ISSUE TITLE
D-Queue Implementation

### ISSUE THREAD

**Issue by rcoder23** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#141]
Implement D-Queue Data - structure .

**Comment by shivanichoudhary12** [comment]
assign this to me

**Comment by Ritu01-git** [comment]
I would like to work on this issue , please assign it to me.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by rcoder23** [comment]
You can work on it. @shivanichoudhary12

**Comment by rcoder23** [comment]
@shivanichoudhary12 Are you still working ?

**Comment by shivanichoudhary12** [comment]
i have make pr already
