### ISSUE TITLE
Calculating Sine funtion using algebra

### ISSUE THREAD

**Issue by XZANATOL** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#145]
# Aim
* Demonestrate how scientific calculators can calculate the Sine function.
* Demonestrate how scientific calculators can deal with negative angles and angles bigger than 360 degrees.

# Details
* Math library will be added for result comparison with that's of the algorithm.
* Math library doesn't support detection of angle quadrants, I can come up with a way to make my algorithm support such a thing.
* User can choose the angle mode. (Degrees/Radians)
* Time Complixities will be provided.

#GSSOC21

**Comment by XZANATOL** [comment]
@Joshitha18 can I get working on this under the mentorship of GSSOC21?

**Comment by rashrey2308** [comment]
@XZANATOL can you please explain what you are trying to implement here?
Are you trying to implement a function that would calculate the sine value of a degree(number)?
Also what exactly do you mean by detection of angle quadrants using sine function?

**Comment by XZANATOL** [comment]
@rashrey2308 Sure,
* The script will calculate Sin(x) where X is an angle (can be in degrees or radians).

* The script will not use any external libraries. (Not going to use math library.. just pure imparative calculations)

* Appologize for the second point, I miss expressed it a bit xd.. I meant to say that the script will also be able to detect the quadrant of the angle and add a negative sign if the angle lies in either 3rd or 4th quadrants
