### ISSUE TITLE
Add String Programs in Python

### ISSUE THREAD

**Issue by neha-b2001** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#15]
Hello, I am **Neha Binwal**, a **GSSoC 2021** participant. 

There are a lot of standard String-related programs that must be covered. These range from _easy_ programs that help beginners, like...
* Reversal of a given string
* Checking if two strings are anagrams of each other

... to _more difficult_ programs, which are competitive programming favourites, such as: 
* String matching/searching using hashing, Rabin-Karp algorithm, or Knuth-Morris-Pratt algorithm
* Length of longest substring with k distinct characters

I will implement these in Python. I will ensure that my code is:

1. Easily readable and understandable
2. Has adequate comments explaining code logic

**Please consider assigning me this issue as a part of GSSoC '21.**

**Comment by pallavidhere23** [comment]
am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by rk05-lenavo** [comment]
I'm a GSSOC'21 participant kindly assign me this issue. under GSSOC'21 I would love to work in this.

**Comment by prathimacode-hub** [comment]
Hey, I'm a GSSOC21 participant. I would like to work on this issue. Can you assign it to me? I have recently worked on string programs in python.
