### ISSUE TITLE
Implementing QuickSort algorithm 

### ISSUE THREAD

**Issue by sherin527** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#151]
Hi @Joshitha18 ma'am, I want to add a python script for the implementation of the Quicksort algorithm. I'm a GSSOC'21 participant pls assign this issue to me.

**Comment by Joshitha18** [comment]
@sherin527 it's already implemented. Please go through repo once. Closing issue

**Comment by sherin527** [comment]
ok, so @Joshitha18 ma'am can I implement BFS in python, I guess that is not done yet.

**Comment by Joshitha18** [comment]
@sherin527 yes you can, create new issue I'll assign you

**Comment by sherin527** [comment]
ok ma'am.
