### ISSUE TITLE
Matrix Transpose (2D Arrays)

### ISSUE THREAD

**Issue by sayantani11** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#160]
Given a square matrix A and its number of rows (or columns) N, return the transpose of A.

**Comment by rcoder23** [comment]
@sayantani11 You can work on it.

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 participant. I would want to work on this issue. I would be highly obliged if you could assign this to me. Thanks!

**Comment by ANAMIKA1410** [comment]
# Python program to get transpose
# elements of two dimension list
def transpose(l1, l2):
 
    # iterate over list l1 to the length of an item
    for i in range(len(l1[0])):
        # print(i)
        row =[]
        for item in l1:
            # appending to new list with values and index positions
            # i contains index position and item contains values
            row.append(item[i])
        l2.append(row)
    return l2

**Comment by sayantani11** [comment]
@rcoder23 I guess you can close the issue
