### ISSUE TITLE
Euclid Algorithm to find GCD

### ISSUE THREAD

**Issue by sayantani11** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#161]
Please assign this issue to me.

**Comment by rcoder23** [comment]
@sayantani11 You can work only one issue at time.

**Comment by Tanvie** [comment]
Please assign this issue to me, I am a GSSoC'21 aspirant.

**Comment by sayantani11** [comment]
I am done with the previous issue can I work on it

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 participant. Could you please assign this issue to me?

**Comment by rcoder23** [comment]
@Tanvie You can work on  it.

**Comment by ANAMIKA1410** [comment]
# Python program to demonstrate Basic Euclidean Algorithm


# Function to return gcd of a and b
def gcd(a, b): 
	if a == 0 :
		return b 
	
	return gcd(b%a, a)

a = 10
b = 15
print("gcd(", a , "," , b, ") = ", gcd(a, b))

a = 35
b = 10
print("gcd(", a , "," , b, ") = ", gcd(a, b))

a = 31
b = 2
print("gcd(", a , "," , b, ") = ", gcd(a, b))
