### ISSUE TITLE
Climbing stairs algorithm

### ISSUE THREAD

**Issue by aaadddiii** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#162]
climbing stairs problem is a classic dynamic programming question asked in many interviews

problem statement :
You are climbing a staircase. It takes n steps to reach the top.
Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?

**Comment by rcoder23** [comment]
@aaadddiii You can work on it.
