### ISSUE TITLE
Armstrong number

### ISSUE THREAD

**Issue by SrishtiArya07** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#164]
An Armstrong number is a positive integer such that the sum of the digits raised to the power of the number of digits is equal to the number itself.
Eg- 153 = 1^3 + 5^3 + 3^3 = 1 + 125 + 27 = 153

I want to add a program that checks if the user entered number is an Armstrong number or not.

As a GSSoC'21 participant, I would like to add the solution to this problem in the Python language.
Please assign it to me.

**Comment by rcoder23** [comment]
@SrishtiArya07 You can work on it.
