### ISSUE TITLE
Fibonacci Search

### ISSUE THREAD

**Issue by Harshpatel2222** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#177]
I would link to add Fibonacci search under GSSOC'21 so can you please assign it to me?

**Comment by rcoder23** [comment]
@Harshpatel2222 You can work on it.

**Comment by iamansoni** [comment]
Is this issue still need to be addressed? If yes, you can assign it to me.
I would like to work on this task!

**Comment by Harshpatel2222** [comment]
I have submitted PR. 
@rcoder23  can you please check and review it?
