### ISSUE TITLE
Add Queue Programs in python

### ISSUE THREAD

**Issue by sanjana-coder** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#18]
Hello, I'm Sanjana, a GSSoC 2021 participant.

Aim:
Add Queue related program with solutions
Standard problems that uses Queue Implementation / Queue based algorithms 

Please assign this issue to me. Thank you.

**Comment by kushal13112001** [comment]
Hey, I am a GSSOC'21 participant. I would like to contribute the code of this problem statement in PYTHON language. Please assign this issue to me. I will add various questions using queues

**Comment by rcoder23** [comment]
@sanjana-coder You can work on this issues.

**Comment by ANAMIKA1410** [comment]
Hello, I'm Anamika, a GSSoC 2021 participant.
i want to contribute for this issue.
 

Please assign this issue to me. Thank you.

**Comment by rcoder23** [comment]
@sanjana-coder unassigned issue after 2 days of inactive.

**Comment by rcoder23** [comment]
@ANAMIKA1410 You can work on it .

**Comment by rcoder23** [comment]
Issue closed No one participating .
