### ISSUE TITLE
Add Binary Tree Implementation and Standard Problems

### ISSUE THREAD

**Issue by sanjana-coder** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#19]
Hello, I'm Sanjana, a GSSoC 2021 participant.

AIM:
I would like to contribute to this repo by adding standard problems / implementations of binary tree
The Python code would be clean, readable, and understandable with the necessary comments.

Please assign this issue to me. Thank you.

**Comment by srisatya1197** [comment]
I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

**Comment by sayantani11** [comment]
I am a GSSoC'21 participant and I would like to work on this issue, so kindly requesting me for assigning this issue.

**Comment by Joshitha18** [comment]
@sayantani11 Please don't make pr if the issue is not assigned to you yet.

**Comment by sayantani11** [comment]
@Joshitha18 sorry for the inconvenience.....But requesting you to assign me this issue so that the code can be merged

**Comment by sayantani11** [comment]
Hi @rcoder23  I still don't have response to the above request
