### ISSUE TITLE
implementation of Graph Algorithms

### ISSUE THREAD

**Issue by VivanVatsa** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#195]
hi, as a GSSOC'21 participant, I would be implementing below listed graph algorithms:

1. Bellman-Ford Algorithm
2. Breadth-First Search
3. Brent's Algorithm for Cycle Detection
4. Depth First Search
5. Dijkstra's Algorithm
6. Floyd-Warshall Algorithm
7. Prim's Algorithm

assign this to me & i will get started with the implementation

**Comment by rcoder23** [comment]
@VivanVatsa You can work on it.

**Comment by rcoder23** [comment]
@VivanVatsa add one solution at one time.

**Comment by VivanVatsa** [comment]
yes @rcoder23 
noted: will add one algorithm at a time
