### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by noviicee** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#2]
Add appropriate links to the Snippets section of the readme.
I would like to work on this issue.

(participant in GSSOC'21)

**Comment by srimontidutta** [comment]
Can I contribute to this project as a part of GSSoC 21?

**Comment by Ananya88** [comment]
Hey !!
I am interested in this project as GSSOC '21 participant .
And I would like to to update the Readme.md file by adding :

1. How to contribute in this project. The procedure from forking to making a pull request.
2. About how to add issues and etc.
3. About the project and how it can help the community/people .

Please assign me with this issue .Thanks.
