### ISSUE TITLE
Strong Number

### ISSUE THREAD

**Issue by rohanbabbar04** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#200]
Strong number is a special number whose sum of factorial of digits is equal to the original number.

**Comment by rohanbabbar04** [comment]
Do assign it to me

**Comment by rohanbabbar04** [comment]
Do assign it to me @rcoder23

**Comment by rcoder23** [comment]
@rohanbabbar04 you can work on it.

**Comment by rcoder23** [comment]
@rohanbabbar04 Create new Pull request . Where Only add Strong Number code in Algebra folder.

**Comment by rohanbabbar04** [comment]
@rcoder23 the PR above only contains the strong number code in the Algebra Folder 
I can't understand why to make a new PR?

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 participant. I would want to work on this issue. I would be highly obliged if you could assign this to me. I will be using Java. Thanks!
