### ISSUE TITLE
ADD Turbo sort in codechef

### ISSUE THREAD

**Issue by srisatya1197** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#203]
I want to add turbo sort code in codechef .Please assign this issue as a part of GSSOC'21 participant.

**Comment by srisatya1197** [comment]
@rcoder23 Sir assign me this issue

**Comment by srisatya1197** [comment]
@Joshitha18 ma'am please assign me this issue

**Comment by rashrey2308** [comment]
Kindly specify the link of the question

**Comment by srisatya1197** [comment]
Thank you for the suggestion. Are you a participant or a mentor?

**Comment by srisatya1197** [comment]
ok ma'am.

**Comment by srisatya1197** [comment]
Question: Given the list of numbers, you are to sort them in non decreasing order.
    Input:
    t – the number of numbers in list, then t lines follow [t <= 10^6].
    Each line contains one integer: N [0 <= N <= 10^6]

   Output:
    Output given numbers in non decreasing order.

  Example:
Input:
5
5
3
6
7
1
Output:
1
3
5
6
7

**Comment by rashrey2308** [comment]
@srisatya1197 I need the link to the question. Not just what the question is. There are various sorting techniques and many of them already exist in the repository. i need to check before assigning the issue to you.

**Comment by srisatya1197** [comment]
ma'am here is the link https://www.codechef.com/problems/TSORT

**Comment by rashrey2308** [comment]
There is nothing unique in this question. Any normal sort can be applied. Closing this issue.
