### ISSUE TITLE
Automorphic Number

### ISSUE THREAD

**Issue by rohanbabbar04** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#208]
A number is called Automorphic number if and only if its square ends in the same digits as the number itself.
Do assign it to me as a part of GSSOC'21 @rcoder23 @Joshitha18

**Comment by rcoder23** [comment]
@rohanbabbar04 You can work on it.

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 participant. I would want to work on this issue. I would be highly obliged if you could assign this to me. I will be using Java. Thanks!

**Comment by rohanbabbar04** [comment]
@khusheekapoor this project is for only python

**Comment by khusheekapoor** [comment]
@rohanbabbar04 I can use Python, C and C++ too!

**Comment by ANAMIKA1410** [comment]
num = int(input("Enter a number \n"))

#square of num
sqr = num**2

#find number of digits in num 
n = len(str(num))

#find last n digits of squar
last = sqr%pow(10,n)

if last == num:
  print("Automorphic Number")
else:
  print("Not an Automorphic Number")

**Comment by ANAMIKA1410** [comment]
@rohanbabbar04 check my code , I wrote above.

**Comment by rohanbabbar04** [comment]
@ANAMIKA1410 
If you want to work on a problem do create an issue and then work on it 
This problem is assigned to me so I'm sorry you can't work on it
