### ISSUE TITLE
Check whether a Number is Armstrong Number or Not.

### ISSUE THREAD

**Issue by starrohan999** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#210]
A program to check whether a number Armstrong number or not.

Armstrong number is the number whose basically the addition of cube of each digit in the number is equal to the number.
example- 153{1*1*1+5*5*5+3*3*3==153}

Input:153

Output: YES

**Comment by starrohan999** [comment]
hey @rcoder23, can you please assign it to me?
I am GSSOC'21 participant.

**Comment by rcoder23** [comment]
@starrohan999 Already Present .
