### ISSUE TITLE
Adding Selection Sort algorithm

### ISSUE THREAD

**Issue by Tarun-Kamboj** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#216]
I would like to add the selection sort algorithm.
Please assign it to me @rcoder23 @Joshitha18

**Comment by ANAMIKA1410** [comment]
# Python program for implementation of Selection 
# Sort 
import sys 
A = list(map(int,input.split()))
  
# Traverse through all array elements 
for i in range(len(A)): 
      
    # Find the minimum element in remaining  
    # unsorted array 
    min_idx = i 
    for j in range(i+1, len(A)): 
        if A[min_idx] > A[j]: 
            min_idx = j 
              
    # Swap the found minimum element with  
    # the first element         
    A[i], A[min_idx] = A[min_idx], A[i] 
  
# Driver code to test above 
print ("Sorted array") 
for i in range(len(A)): 
    print("%d" %A[i]),

**Comment by Tarun-Kamboj** [comment]
> # Python program for implementation of Selection
> # Sort
> import sys

Thanks for your concern but I know how to implement Selection Sort, that's why I opened the issue in the first place :)
