### ISSUE TITLE
Interesting XOR!

### ISSUE THREAD

**Issue by rohanbabbar04** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#218]
You are given an integer C. Let d be the smallest integer such that 2^d is strictly greater than C.
Consider all pairs of non-negative integers (A,B) such that A,B<2d and A⊕B=C (⊕ denotes the bitwise XOR operation). Find the maximum value of A⋅B over all these pairs.
Constraints 
1≤T≤10^5
1≤C≤10^9
 
This is a good level greedy problem with difficult constraints

**Comment by rohanbabbar04** [comment]
@rcoder23 Do assign this to me

**Comment by rcoder23** [comment]
@rohanbabbar04 You can work on it.
