### ISSUE TITLE
Implement binary search tree

### ISSUE THREAD

**Issue by aaadddiii** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#227]
Binary Search Tree is a node-based binary tree data structure . The left subtree of a node contains only nodes with keys lesser than the node's key. The right subtree of a node contains only nodes with keys greater than the node's key.

**Comment by Dhanush2612** [comment]
@aaadddiii 
Can you assign me this issue?

**Comment by sayantani11** [comment]
This issue is already there

**Comment by Ananya9878** [comment]
Please assign this to me.

**Comment by sayantani11** [comment]
This issue is already done under #19 and is closed.
