### ISSUE TITLE
AVL Treee and BST in python and C++

### ISSUE THREAD

**Issue by avishmehta68710** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#23]
hi 
i am GSSOC participant and would like to work on this issue. please assign it to me

**Comment by OnewayShruti** [comment]
Hey 
I am a GSSOC'21 participant(Discord Username -Oneway_Shruti(P)#9537)
I wish to contribute to AVL Treee and BST in python and C++ . I can write the code in C++ and also in python, along with explanatory comments.
Do consider assigning me on this.

**Comment by rcoder23** [comment]
@OnewayShruti This repository only containts Python Code. Create New Issue for this
