### ISSUE TITLE
Painting Fence algorithm | Dynamic Programming | GSSoC'21 | Python

### ISSUE THREAD

**Issue by Harikrishnan6336** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#235]
I would like to implement Painting Fence algorithm as part of GSSoC'21. Kindly assign me this issue. @rcoder23  @Joshitha18.

**Comment by Harikrishnan6336** [comment]
@rcoder23  Kindly assign me this issue

**Comment by rcoder23** [comment]
@Harikrishnan6336 you can work on it.
