### ISSUE TITLE
Largest Rectangle in a Histogram

### ISSUE THREAD

**Issue by sayantani11** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#238]
Given an array. Each element represents the height of the histogram's bar and the width of each bar is 1, find the area of the largest rectangle in the histogram.

Assign to me please.

**Comment by JASKAMAL22** [comment]
hello @admins ,I would like to work on it. Kindly assign it to me:)

**Comment by sayantani11** [comment]
@rcoder23 I guess this issue can be closed
