### ISSUE TITLE
Keypad phone problem

### ISSUE THREAD

**Issue by sayantani11** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#239]
Print all possible words from a keypad phone.

**Comment by sayantani11** [comment]
Please assign to me.

**Comment by rashrey2308** [comment]
Please elaborate

**Comment by sayantani11** [comment]
@rashrey2308  Using the concept the recursion we will try printing all possible words that can be formed by the old keypad phones like for example Nokia......Basically an advanced permutation question that uses recursion
