### ISSUE TITLE
[GSSOC'21] Sorting algorithm implementation in python

### ISSUE THREAD

**Issue by sayantikag98** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#24]
Hi, I am Sayantika participating in GSSOC '21. I want to implement O(n^2) and O(nlogn) sorting algorithms in python.

Please assign this task to me.

Thank you.

**Comment by Pranjal-2001** [comment]
I am a participant in GSSOC'21. I would like to work on thid issue. Could you please assign it to me?

**Comment by kashika0112** [comment]
I am a participant in GSSOC'21 and would also like to contribute to this issue. Please assign it to me!

**Comment by Joshitha18** [comment]
@sayantikag98 You can work on this issue

**Comment by sayantikag98** [comment]
Sure

**Comment by sayantikag98** [comment]
[GSSOC'21] Added Sorting algorithm implementation in python #24 #56
