### ISSUE TITLE
Count Inversion

### ISSUE THREAD

**Issue by sayantani11** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#241]
Count the inversion in the given array,
Two elements a[i] and a[j] form an inversion if a[i]>a[j] and i<j

**Comment by sayantani11** [comment]
please assign it to me.

**Comment by sayantani11** [comment]
@rcoder23 please assign this to me

**Comment by sayantani11** [comment]
@rcoder23 @Joshitha18 please assign the issue to me

**Comment by sayantani11** [comment]
@rashrey2308  assign pleasee

**Comment by sayantani11** [comment]
@rashrey2308  Please assign me this issue

**Comment by rcoder23** [comment]
@sayantani11 You can work on it.

**Comment by sayantani11** [comment]
@rcoder23 I think this issue can be closed now
