### ISSUE TITLE
Power of Three

### ISSUE THREAD

**Issue by JASKAMAL22** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#247]
Given an integer n, return true if it is a power of three. Otherwise, return false.

An integer n is a power of three, if there exists an integer x such that n == 3x.

Example 1:

Input: n = 27
Output: true
Example 2:

Input: n = 0
Output: false

Constraints:
-231 <= n <= 231 - 1

**Comment by JASKAMAL22** [comment]
Hello @rcoder23 @rashrey2308 , I want to work on it as a part of gssoc21. Kindly assign it to me :)

**Comment by rcoder23** [comment]
@JASKAMAL22 You can work on it.
