### ISSUE TITLE
Add Chinese remainder theorem 

### ISSUE THREAD

**Issue by srisatya1197** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#25]
I want to add Chinese remainder theorem in python . Can I add as it's not there in the repo . If yes Could you please assign me as a part of GSSOC'21

**Comment by Joshitha18** [comment]
@srisatya1197 U can work on this issue

**Comment by rk05-lenavo** [comment]
I'm a GSSOC'21 participant kindly assign me this issue. I would love to work in this.

**Comment by srisatya1197** [comment]
@Joshitha18 thank you ma'am

**Comment by srisatya1197** [comment]
@rk05-lenavo @Joshitha18 ma'am assigned me so go for the other issue

**Comment by rcoder23** [comment]
@srisatya1197 Closing issue because no one active .

**Comment by srisatya1197** [comment]
@rcoder Sir I completed this issue that was 3 days ago and I also mentioned in discord channel .Please check my  pull request  #118
