### ISSUE TITLE
Prim's and Kruskal's Minimum Spanning Tree Algorithms

### ISSUE THREAD

**Issue by debjitpal5040** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#254]
Both Prim's and Kruskal's algorithms are used in a Graph to find a minimum spanning tree. These two are most basic yet important algorithms for finding a MST in a Graph. I would like to add these two programs in Graphs directory. Please assign this to me, I am a GSSOC participant.

**Comment by debjitpal5040** [comment]
Hello @rcoder23 I want to work with this, please assign this to me

**Comment by rcoder23** [comment]
@debjitpal5040 You can work on it.
