### ISSUE TITLE
Add LCS(Longest common Subsequence) in python 

### ISSUE THREAD

**Issue by NEERAJAP2001** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#26]
Hello !! I'd like to contribute to this issue @i-tick, Please assign this to me.(as part of GSSOC-21)
The Python code would be clean, readable comments.

Thank you

**Comment by Joshitha18** [comment]
@NEERAJAP2001 You can start working on this issue

**Comment by rk05-lenavo** [comment]
I'm a GSSOC'21 participant kindly assign me this issue. I would love to work in this.

**Comment by Joshitha18** [comment]
@rk05-lenavo This issue is already assigned. You can choose or create a new issue
