### ISSUE TITLE
Decimal to all other forms

### ISSUE THREAD

**Issue by sayantani11** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#269]
A function that would convert decimal to binary, octal and Hexadecimal.

**Comment by Ananya9878** [comment]
Pls assign this issue to me

**Comment by rashrey2308** [comment]
@sayantani11 do you wanna be assigned or should I assign it to ananya?

**Comment by sayantani11** [comment]
Assign to Ananya @rashrey2308
