### ISSUE TITLE
Add Questions and Solutions on Linked-Lists

### ISSUE THREAD

**Issue by NEERAJAP2001** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#27]
As part of this directory - [url](https://github.com/Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo/tree/main/Topic%20Wise%20Questions%20with%20Solutions)

I would like to add some questions based on Linked-Lists along with their solutions.
The Python code would be clean with readable comments.

Please assign this issue to me as part of GSSOC-21, Thank you.

**Comment by Joshitha18** [comment]
@NEERAJAP2001 mention the questions u want to add

**Comment by NEERAJAP2001** [comment]
Here is a curated list @Joshitha18 

1.Reverse a Doubly Linked List
2.Intersection Point in Y Shaped Linked Lists
3.Given a linked list of 0s, 1s and 2s, sort it 

I'll add more questions once I complete these!!
Thanks

**Comment by Joshitha18** [comment]
@NEERAJAP2001 you can start working on the above 3 questions

**Comment by NEERAJAP2001** [comment]
Here are the Next 3 Questions I'll be adding once this #142 Gets Merged:
1. Add two Numbers represented by LL
2. Remove Duplicates from unsorted LL
3. Find the first bode of the loop in a LL

Thanks.
