### ISSUE TITLE
Insertion Sort

### ISSUE THREAD

**Issue by aaadddiii** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#277]
Insertion sort is the sorting mechanism where the sorted array is built having one item at a time. The array elements are compared with each other sequentially and then arranged simultaneously in some particular order.
Hi ,
I am a GSSOC  participant , I would like to implement insertion sort in python .

**Comment by rcoder23** [comment]
@aaadddiii You can work on it.
