### ISSUE TITLE
Rat in a Maze problem

### ISSUE THREAD

**Issue by PriyanshuChatterjee** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#285]
Rat in a maze is a problem that is solved using a backtracking algorithm in graphs. Here the Rat maze problem will be solved with Python3. 

I'm a GSSoc Participant and will like to work on this.

**Comment by PriyanshuChatterjee** [comment]
@rcoder23 @rashrey2308 Please assign me this.

**Comment by rcoder23** [comment]
@PriyanshuChatterjee Already pull request created for that. #131
