### ISSUE TITLE
Z Algorithm

### ISSUE THREAD

**Issue by Rutuja-Kolte** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#29]
Hello! I want to contribute to this project by adding the Z Algorithm, please assign the issue to me, I will provide a clean code along with proper documentation

**Comment by Joshitha18** [comment]
@Rutuja-Kolte u can work on it

**Comment by Rutuja-Kolte** [comment]
Thanks

**Comment by rcoder23** [comment]
Closing due to inactive
