### ISSUE TITLE
Add Knuth–Morris–Pratt Algorithm

### ISSUE THREAD

**Issue by srisatya1197** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#295]
I saw the issue regarding Knuth–Morris–Pratt Algorithm as this was assigned but I really don't think assignee is active . I want to work on this issue as I'm a participant of GSSOC'21 . @rcoder23 Sir or @Joshitha18 ma'am Please assign me this issue

**Comment by rohanbabbar04** [comment]
@srisatya1197 this issue is already assigned to me do take up a different issue #250

**Comment by srisatya1197** [comment]
are you working on it or can I aid ?

**Comment by rohanbabbar04** [comment]
I am working on it and it is almost done
