### ISSUE TITLE
Implement Sieve of Eratosthenes. (GSSOC '21)

### ISSUE THREAD

**Issue by ShubhamGupta577** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#30]
## Sieve of Eratosthenes
Sieve of Eratosthenes is an algorithm for finding all the prime numbers in a range of 2 to N.

### Implementation
In the beginning, we write down all numbers between 2 and N. We mark all proper multiples of 2 (since 2 is the smallest prime number) as composite. A proper multiple of a number x, is a number greater than x and divisible by x. Then we find the next number that hasn't been marked as composite, in this case, it is 3. This means 3 is prime, and we mark all proper multiples of 3 as composite. The next unmarked number is 5, which is the next prime number, and we mark all proper multiples of it. And we continue this procedure until we processed all numbers in the row.
* **Time complexity - O(N*log logN)**
* **Space complexity - O(N^0.5)**

**Comment by ShubhamGupta577** [comment]
I want to work on this under GSSOC '21. Please assign me this.

**Comment by Joshitha18** [comment]
@ShubhamGupta577 U can work on this issue

**Comment by rk05-lenavo** [comment]
I'm a GSSOC'21 participant kindly assign me this issue. I would love to work in this.
