### ISSUE TITLE
Detecting loops within a linked list

### ISSUE THREAD

**Issue by RohiniRG** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#310]
This python code will be able to detect loops and even self-loops forming within the nodes of a linked list.
I am a GSSOC'21 participant

**Comment by rcoder23** [comment]
@RohiniRG You can work on it.

**Comment by rcoder23** [comment]
Add solution in Master-PyAlgo/Topic Wise Questions with Solutions/Linked List/  folder .

**Comment by RohiniRG** [comment]
@rcoder23 have a look
