### ISSUE TITLE
Add convert the string codechef program

### ISSUE THREAD

**Issue by srisatya1197** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#323]
I want to add convert the string program in codechef directory.
Link for the program : https://www.codechef.com/problems/CONVSTR
Please assign me this issue @rashrey2308 ma'am

**Comment by srisatya1197** [comment]
@rcoder23 @rashrey2308 @Joshitha18 assign me this issue.

**Comment by srisatya1197** [comment]
@rcoder23 Sir can you please assign me this issue?

**Comment by rcoder23** [comment]
add question releated to some data -structures . and mostly asked
