### ISSUE TITLE
Pronic Numbers

### ISSUE THREAD

**Issue by ShrutiOmer** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#335]
I want to add pronic number program which generates all pronic numbers in given range.
A pronic number is a number which is the product of two consecutive integers, that is, a number of the form n(n + 1). The first few pronic numbers are: 0, 2, 6, 12, 20, 30, 42, 56, etc.

Please assign this issue to me.

**Comment by rcoder23** [comment]
@ShrutiOmer You can work on it.
