### ISSUE TITLE
Merge Without Extra Space

### ISSUE THREAD

**Issue by ASLManasa** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#336]
problem  : Given two sorted arrays arr1[] and arr2[] of sizes n and m in non-decreasing order. Merge them in sorted order without using any extra space. Modify arr1 so that it contains the first N elements and modify arr2 so that it contains the last M elements.

I have taken this problem from geeksforgeeks. I am a gssoc'21 particpant and I want to contribute to this. Kindly assign me this.

**Comment by rcoder23** [comment]
@ASLManasa already present in Master-PyAlgo/Topic Wise Questions with Solutions/Array/
