### ISSUE TITLE
Adding Geometry program in python [GSSOC'21]

### ISSUE THREAD

**Issue by deepshikha007** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#34]
Hey, I'm Deepshikha GSSOC participant.

I would like to contribute the code for the **Convex Hull Problem** using Jarvi's Algorithm.
The Python code would be clean, readable, and understandable with the necessary comments.

Please assign this issue to me.

**Comment by ANAMIKA1410** [comment]
Hey, I'm Anamika, a  GSSOC participant.

I would like to contribute the code for the Problem u.
The Python code would be clean, readable, and understandable with the necessary comments.

Please assign this issue to me.
