### ISSUE TITLE
Add two numbers in linkedlist directory.

### ISSUE THREAD

**Issue by srisatya1197** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#341]
You are given two non-empty linked lists representing two non-negative integers.
The digits are stored in reverse order and each of their nodes contain a single digit.
Add the two numbers and return it as a linked list.
You may assume the two numbers do not contain any leading zero, except the number 0 itself.
Input: 2 -> 4 -> 3, 5 -> 6 -> 4
Output: 7 -> 0 -> 8
Output explanation: 342 + 465 = 807
@rcoder23 @rashrey2308 @Joshitha18 can you please check this question if it's ok. Then, I'll solve it and keep it in a suitable directory.

**Comment by rcoder23** [comment]
One issue at time.

**Comment by srisatya1197** [comment]
@rcoder23  Can I get the explanation for closing this issue. So that I will not repeat it.
