### ISSUE TITLE
Longest prefix sufix

### ISSUE THREAD

**Issue by ShrutiOmer** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#358]
I want to add a program which will give the longest proper prefix which is proper suffix also in the string.
Ex-abab: length is 2 as ab is proper prefix and suffix
     aaaa: length is 3 as aaa is proper prefix and suffix

Please assign me this issue.

**Comment by rcoder23** [comment]
You can work on it. @ShrutiOmer
