### ISSUE TITLE
One Away

### ISSUE THREAD

**Issue by ASLManasa** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#360]
There are three types of edits that can be performed on strings: insert a character, 
remove a character, or replace a character. Given two strings, write a function to check if they are 
one edit (or zero edits) away
 
I am a gssoc'21 participant and want to work on this kindly assign me this . Thanks.

**Comment by ASLManasa** [comment]
@rcoder23 Sir, Can you Please check. Thank you.

**Comment by rcoder23** [comment]
@ASLManasa You can work on it.
Add solution with proper comments.
