### ISSUE TITLE
ADD Kamenetsky’s formula for counting digits in factorial

### ISSUE THREAD

**Issue by dikshajoshi18** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#37]
CAN I ADD "Count digits in a factorial" IN O(1) TIME.
it will be helpful in faster calculations.
discord: diksha#6684
@i-tick #gssoc'21

**Comment by rcoder23** [comment]
Closing due to inactive.

**Comment by dikshajoshi18** [comment]
I hve already added pr
