### ISSUE TITLE
Merge Sort A Linked List

### ISSUE THREAD

**Issue by Prerna-07** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#381]
I am Prerna Chitransh, a GSSOC'21 participant.

Task :
MergeSort A linkedlist

Time Complexity : O(nlogn)

@rcoder23  Please Assign this issue to me

**Comment by Prerna-07** [comment]
@rcoder23  Please Assign this issue to me

**Comment by rcoder23** [comment]
@Prerna-07 You can work on it. And add solution in specific folder

**Comment by Prerna-07** [comment]
@rcoder23 ok sir
