### ISSUE TITLE
Decagonal Number

### ISSUE THREAD

**Issue by rohanbabbar04** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#390]
A decagonal number is a figurate number that extends the concept of triangular and square numbers to the decagon (a ten-sided polygon).

Do assign me this issue @rcoder23

**Comment by rohanbabbar04** [comment]
Do assign me this issue @rcoder23

**Comment by rcoder23** [comment]
@rohanbabbar04 You can work on it.
