### ISSUE TITLE
Reverse_array python

### ISSUE THREAD

**Issue by ChetasShree** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#4]
Hi , I want to solve this issue using python...
Please assign this issue to me under GSSOC 21 ,using python language.
Looking forward to contribute here...

**Comment by ChetasShree** [comment]
Please check in the pull request, there under " Changed the function ", I have submitted the code.

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by simarjeet30** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,Cand python .Also good at DSA.
I know many ways to do it :
1)Using the reversed()/reverse() built-in function.
2)Using the slicing technique.

**Comment by kushal13112001** [comment]
Hey, I am a GSSOC'21 participant. I would like to contribute the code of this problem statement in PYTHON language. Please assign this issue to me.

**Comment by rcoder23** [comment]
Create New Issue . We will Assign to You . @kushal13112001 @simarjeet30 @pallavidhere23 @ChetasShree
