### ISSUE TITLE
Bitwise AND

### ISSUE THREAD

**Issue by Manasi2001** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#410]
Given set S = {1,2,3,....,N), the aim is to find two integers, I and J (where I<J), from set S such that the value of I&J is the maximum possible and also less than a given integer, K. '&' represents bitwise AND operator.

Sample Test Case:
Input: 
3       
5 2     
8 5     
2 2 
Output: 
1
4
0

I'm a GSSoC'21 participant, would like to work on this.

**Comment by rcoder23** [comment]
@Manasi2001 You can work on it. add solution with proper explaination
