### ISSUE TITLE
Palindrome Checker

### ISSUE THREAD

**Issue by Manasi2001** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#415]
The aim is to analyze the entered word and output whether it is a palindrome or not.
 
Sample Test Case:
Input:
level
Output:
The word, level, is a palindrome.

I'm a GSSoC'21 participant, would like to work on this.

**Comment by rcoder23** [comment]
@Manasi2001 Alredy present

**Comment by Manasi2001** [comment]
@rcoder only 2 programs sounding similar to this are present- 'Distinct-Palindromic-Substrings' and 'Longest-Palindromic-Substring', but the code(and the purpose of the code) is different. Mine could also be a different variation of the programs related to palindromes that are present in the list. Please can you review it again?
