### ISSUE TITLE
Special Number

### ISSUE THREAD

**Issue by Khushi-agarwal** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#417]
I want to add the code of special number. A number is special if the sum of the factorial of its digits is equal to the number itself.
Example-145
Please assign me this issue under GSSOC. @rcoder23

**Comment by Khushi-agarwal** [comment]
@rashrey2308 please assign me this issue.

**Comment by rcoder23** [comment]
@Khushi-agarwal you can work on it.
