### ISSUE TITLE
Count pairs with given sum in python 

### ISSUE THREAD

**Issue by soumik2012** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#440]
## 🚀 Feature

Given an array of integers, and a number ‘sum’, find the number of pairs of integers in the array whose sum is equal to ‘sum’.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes 

## Motivation

To contributing to gssoc'21

## Pitch

Input  :  arr[] = {1, 5, 7, -1}, 
          sum = 6
Output :  2
Pairs with sum 6 are (1, 5) and (7, -1)

**Comment by soumik2012** [comment]
@rashrey2308 @rcoder23 @Joshitha18 please assgin me the issue

**Comment by prakharshreyash15** [comment]
Please assign me this issue @rashrey2308 @rcoder23 @Joshitha18

**Comment by rcoder23** [comment]
@soumik2012 You can work on it
