### ISSUE TITLE
More Data Structures 

### ISSUE THREAD

**Issue by rohanbabbar04** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#464]
@rcoder23 
I would like to implement more data structures Do assign me this issue

**Comment by rcoder23** [comment]
@rohanbabbar04 name the specific data- structure you want to work ?

**Comment by rohanbabbar04** [comment]
I will work on all in the last 10 days 
Do assign me this issue

**Comment by rcoder23** [comment]
@rohanbabbar04 Name all the data structure You are going to implement .

**Comment by rohanbabbar04** [comment]
Some are
AVL TREE
BEST FIT
circular linked lists(single double both) 
First fit 
Invert binary tree 
And many more

**Comment by rcoder23** [comment]
@rohanbabbar04 You can work on it,

**Comment by rcoder23** [comment]
@rohanbabbar04 First check the data-structure is alredy present or not. If not then make PR.

Create spearate PR for one data-structure .So marks can be easily give for GSSOC21

**Comment by rohanbabbar04** [comment]
Thanks do assign me this issue

**Comment by rohanbabbar04** [comment]
> @rohanbabbar04 First check the data-structure is alredy present or not. If not then make PR.
> 
> Create spearate PR for one data-structure .So marks can be easily give for GSSOC21

Yes I'll do it @rcoder23

**Comment by rohanbabbar04** [comment]
Shouldn't data structures be labelled level 3
