### ISSUE TITLE
Hourglass Sum

### ISSUE THREAD

**Issue by Manasi2001** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#467]
Given a 6X6 2D Array, A:
1 1 1 0 0 0
0 1 0 0 0 0
1 1 1 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0

An hourglass in A is a subset of values with indices falling in this pattern in A's graphical representation:
a b c
  d
e f g

There are 16 hourglasses in A, and an hourglass sum is the sum of an hourglass' values. Like here, the maximum hourglass sum is 7 for the hourglass in the top left corner.

The aim is to check all such hourglasses and print the maximum hourglass sum for the 2D array entered by user.

**Comment by rcoder23** [comment]
@Manasi2001 You can only work one issue at time .

Don't make pull request before assigning issue.

**Comment by Manasi2001** [comment]
> @Manasi2001 You can only work one issue at time .
> 
> Don't make pull request before assigning issue.

![image](https://user-images.githubusercontent.com/68627617/119215850-ebbd4f80-baed-11eb-8b59-35d7cdff7220.png)

@rcoder even after 12 days of opening the issue, if no one is assigning it to me (I also repeatedly requested for the same here and on Discord as well), then what else I'm I supposed to do? The program is about to end in a week and if it goes on like this, I'll hardly be able to make any contribution.😔 
But, I understand your point of view as well. So many people, so many contribution to attend to. For now, please check all of my PRs, next time onwards I'll again stick to waiting for you to assign my issues to me.
