### ISSUE TITLE
adding greedy algorithms in python

### ISSUE THREAD

**Issue by robin025** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#488]
**Is your feature request related to a problem? Please describe.**
Hey @rcoder23  I would like to add all major greedy  algorithms like Fractional Knapsack
Huffman Coding, Activity Selection Problem, Egyptian Fraction in python language

**Do you want to work on it**
Yes
I will implement this in python language

Kindly Assign me this under GSSOC 21
Thank you

**Comment by rcoder23** [comment]
@robin025 you can work on it

**Comment by rcoder23** [comment]
Make separate PR for one program

**Comment by robin025** [comment]
> Make separate PR for one program

Ok @rcoder23
