### ISSUE TITLE
Dijkstra's Algorithm

### ISSUE THREAD

**Issue by pranita736** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#49]
I have sent the pull request for the implementation of Dijkstra's Algorithm using Python. 

Please assign this issue to me.

**Comment by Joshitha18** [comment]
@rcoder23 check this [https://github.com/Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo/pull/20#issue-588144171](PR)

**Comment by Joshitha18** [comment]
@rcoder23 check this PR https://github.com/Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo/pull/20
