### ISSUE TITLE
Numerical algos

### ISSUE THREAD

**Issue by akshitadixit** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#5]
Hi, I would like to work on the numerical folder in Python

**Comment by kshittijagrawal** [comment]
Hey there!
I'd like to contribute to the project. I want to address and fix this issue. My implementation will be in python with a clean code and documentation. Kindly provide me with this issue.
I'm also a GSSOC'21 participant.

**Comment by akshitadixit** [comment]
@vaishnavipatil29 @BeAgarwal @i-tick
