### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by Joshitha18** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#51]
Given a sorted array of n elements, write a binary search algorithm to search a given element x in array.

**Comment by swarnalii** [comment]
Can I work on this?

**Comment by Joshitha18** [comment]
@swarnalii u can work on this issue

**Comment by ChetasShree** [comment]
Can I work on the issues??, I will solve this using the python language

**Comment by GarimaKhare15** [comment]
Can I work on this issue ?
