### ISSUE TITLE
Addition of Machine Learning Projects

### ISSUE THREAD

**Issue by Manasi2001** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#510]
@rcoder23 as the name of the project has 'PyAlgo' in it, I think we should definitely have ML projects(built using multiple algorithms like regression, classification, clustering, etc.) written in python as well. An another folder named 'Machine Learning' could be created and in that ipynb files could be added. 
I've also built some projects like Solar Radiation Prediction, Flight Delay Prediction, E-Mail Classification, Amazon Alexa Reviews Analysis (NLP), etc. that I would like to add under this. Please give your suggestion :)

**Comment by rcoder23** [comment]
@Manasi2001 It is good idea to add Machine Learning Algorithms here.
But i am mentor of this project . I can't make changes in this project .

Project Maintainer can do it.
