### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by Swetha126** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#52]
## Bubble Sort in Python

I would like to contribute the code for bubble sort in python with the appropriate comments and  sample test cases.
I will add the time and space complexity also.

I'm a GSSOC'21 participant.
Please assign me this issue

**Comment by Joshitha18** [comment]
@Swetha126 u can work on this issue

**Comment by Swetha126** [comment]
I have created a pull request for this issue.
Do check and let me know the changes if any.
Thank you!
