### ISSUE TITLE
Insertion Sort

### ISSUE THREAD

**Issue by Swetha126** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#54]
## Insertion sort in python

I would like to contribute the code for insertion sort in python with the appropriate comments and sample test cases.
I will add the time and space complexity also.

I'm a GSSOC'21 participant.
Please assign me this issue

**Comment by eishagoel15** [comment]
I am a Gssoc'21 participant and I want to contribute to this issue by writing the code for this problem in python. So plz assign this issue to me.

**Comment by Joshitha18** [comment]
already implemented in #24 so closing this issue
