### ISSUE TITLE
Checking strings are Anagram or not. (GSSOC '21)

### ISSUE THREAD

**Issue by ShubhamGupta577** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#55]
### Which are **Anagram String**?
Two strings are anagrams if they are made of the same letters either arranged differently or the same. (ignoring the uppercase and lowercase
Examples -
* **Silent** and **Listen**
* **Triangle** and **Integral**
* **This is a string** and **Is this a string**

**Comment by ShubhamGupta577** [comment]
I want to work on this under GSSOC '21. Please assign me this.

**Comment by Joshitha18** [comment]
@ShubhamGupta577 u can work on it

**Comment by riyalalwani19** [comment]
I also want to work on it. Is it possible to assign it to me?

**Comment by GarimaKhare15** [comment]
Hii , I'm a gssoc'21 participant . I want to work on this issue . Please assign this to me @Joshitha18 @ShubhamGupta577 .

**Comment by Joshitha18** [comment]
@GarimaKhare15 it's already assigned.
