### ISSUE TITLE
program to check if given string is pangram or not

### ISSUE THREAD

**Issue by ankan1811** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#59]
Given a string, write a program to check if that string is Pangram or not. A pangram is a sentence containing every letter in the English Alphabet.
Example:
Input : The quick brown fox jumps over the lazy dog
Output : Yes

Input : abcdefgxyz
Output : No

**Comment by ankan1811** [comment]
I want work on this issue as a part of GSSoC'21.Please assign it to me.

**Comment by Joshitha18** [comment]
@ankan1811 u can work on this issue

**Comment by simr-saini** [comment]
Worked on this issue as a part of GSSoC'21.Kindly refer.

**Comment by ankan1811** [comment]
The issue is assigned to me @simr-saini .You cannot work on any issue which is not assigned to you.

**Comment by simr-07** [comment]
I regret the inconvenience caused. Actually I'm a newbie to open source. It was asked that you _can contribute to the project you want to_, so I wrongly did @ankan1811
