### ISSUE TITLE
Tower Of Hanoi

### ISSUE THREAD

**Issue by rohanbabbar04** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#63]
The Tower of Hanoi is one of the main application of recursion. It says "if you can solve n-1 cases, then you can easily solve the nth case". Tower of Hanoi, is a mathematical puzzle which consists of three towers (pegs) and more than one rings is as depicted. These rings are of different sizes and stacked upon in an ascending order, i.e. the smaller one sits over the larger one. The problem is to move all these rings from pole A to pole C using the pole B as spare pole while maintaining the same order. The main issue is that the smaller disk must always come above the larger disk.

I would like to work on it as a part of GSSOC 21.

**Comment by rohanbabbar04** [comment]
Do assign me @Joshitha18

**Comment by sayantani11** [comment]
Hi @Joshitha18 I would like to work on this issue.....Please assign me this
