### ISSUE TITLE
Reverse String Variation in python

### ISSUE THREAD

**Issue by starrohan999** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#65]
**Write a program to reverse a string with some variation.**
The reverse string is a common question but this is not a common question it has some variation in it that makes this question a special question asked by the top MNC of the world.

**input**  "i.like.open.source.contribution.very.much"

**output**  "much.very.contribution.source.open.like.i"

**Comment by starrohan999** [comment]
I want work on this issue as a part of GSSoC'21.Please assign it to me. @Joshitha18

**Comment by starrohan999** [comment]
please assign it to me.
it is my first issue if you find valid so please assign it to me.

**Comment by Joshitha18** [comment]
@starrohan999 you can work on it

**Comment by starrohan999** [comment]
thank you so much.

**Comment by starrohan999** [comment]
so can I create a new folder or put it into a string folder?

**Comment by starrohan999** [comment]
@Joshitha18  please tell me

**Comment by Joshitha18** [comment]
Create a folder 'Reverse_String_Variation' in string folder. Add readme.txt as well explaining question with an example

**Comment by starrohan999** [comment]
ok
