### ISSUE TITLE
Bellman-Ford Algorithm

### ISSUE THREAD

**Issue by XZANATOL** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#8]
I would like to work on this under the mentorship of GSSOC21.

# Details
* Code will be well commented that it describes the code flow and approach steps for the algorithm.
* Test cases will be provided at the end of the code.

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.
