### ISSUE TITLE
Sort array of 0,1,2 without using any sorting algo

### ISSUE THREAD

**Issue by Joshitha18** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#80]
Given an array which consists of only 0, 1 and 2. Sort the array without using any sorting algo

Add in Topic Wise Questions with Solutions/Array.

**Comment by Bayesian4042** [comment]
hey @Joshitha18 I would like to work on this problem.

**Comment by Joshitha18** [comment]
@Bayesian4042 u can work on it. Make sure to add different ways to solve the problem
