### ISSUE TITLE
Move all the negative elements to one side of the array 

### ISSUE THREAD

**Issue by Joshitha18** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#81]
An array contains both positive and negative numbers in random order. Rearrange the array elements so that all negative numbers appear before all positive numbers.

Add in Topic Wise Questions with Solutions/Array.

**Comment by Bayesian4042** [comment]
hey @Joshitha18 , I would like to work on this issue. is it possible to work on it ?

**Comment by Joshitha18** [comment]
@Bayesian4042 issue assigned, u can work on it
