### ISSUE TITLE
Union and Intersection of the two sorted arrays.

### ISSUE THREAD

**Issue by Joshitha18** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#82]
Find the Union and Intersection of the two sorted arrays.

Add in Topic Wise Questions with Solutions/Array.

**Comment by Swetha126** [comment]
I'm a GSSOC'21 participant.
I would like to contribute the code for this. Can you please assign me this issue?

**Comment by Swetha126** [comment]
@Joshitha18 i have opened a pull request for this issue.
Do have a look at it and let me know the changes if any.
Thank you!!
