### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#86]
Hi ! I would like to create a file named contributing.md which will
Add the following -

1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on this as a part of GSSOC'21

**Comment by Ritu01-git** [comment]
please assign it to me

**Comment by khareyash05** [comment]
@Ritu01-git i am a participant of GSSOC'21 and i have self created the issue
Sorry!

**Comment by rcoder23** [comment]
@khareyash05 At present time , No one Allow To update Readme file.

**Comment by khareyash05** [comment]
@rcoder23 ok so can I create a new file?
