### ISSUE TITLE
GCD_LCM in python

### ISSUE THREAD

**Issue by ChetasShree** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#9]
I want to solve this issue using python...
Please assign this issue to me under GSSOC 21, using python language.
Looking forward to contribute here...

Please check in the pull request, there under " Changed the function ", I have submitted the code.

**Comment by kshittijagrawal** [comment]
Hey there!
I'd like to contribute to the project. I want to address and fix this issue. My implementation will be in python with a clean code and documentation. Kindly provide me with this issue.
I'm also a GSSOC'21 participant.

**Comment by HarinandhanPSGiTech** [comment]
Hey, I would love to contribute to the project. I will  put forth my best and provide the best  code I can  and hope that will help you !
I too am a GSSOC'21 participant.

**Comment by pi-squared-4** [comment]
I am a GSSOC'21 participant. I would love to work on this, can you assign this to me. <3

**Comment by rcoder23** [comment]
Already Solved .
