### ISSUE TITLE
Linear Search

### ISSUE THREAD

**Issue by javeed3157** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#93]
I would like to implement Insertion Sort .
I am GSSOC'2021 participant
Please assign me this issue

**Comment by Joshitha18** [comment]
@javeed3157 u mean u want to implement linear search?

**Comment by javeed3157** [comment]
> @javeed3157 u mean u want to implement linear search?

Yes LinearSearch in python

**Comment by Harikrishnaa3131** [comment]
I would like to implement binary search

**Comment by javeed3157** [comment]
> I would like to implement binary search

@Harikrishnaa3131  I think #51 is binary search

**Comment by GarimaKhare15** [comment]
Hii , I'm a gssoc'21 participant . I would like to implement binary search in python .
Please assign this to me @Joshitha18 @Harikrishnaa3131 @javeed3157 @BeAgarwal @vaishnavipatil29 .

**Comment by javeed3157** [comment]
@Joshitha18  in which folder should I add my code

**Comment by Joshitha18** [comment]
@GarimaKhare15 Binary Search issue is already assigned. Check for the issues that are not assigned or create new, i will assign them to you

**Comment by Joshitha18** [comment]
@javeed3157 add the file in a new folder 'Search' in Algorithms.

**Comment by javeed3157** [comment]
@Joshitha18 should I update readme file as well or  just code in  a new folder

**Comment by Joshitha18** [comment]
just code with proper comments and an example input output @javeed3157
