### ISSUE TITLE
String Searching Algorithms

### ISSUE THREAD

**Issue by neha-b2001** [Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo#98]
String searching or matching is a very important algorithmic concept. 

I would like to implement Python programs for the following **String searching algorithms**:
- Hashing
- Rabin-Karp Algorithm 

**Please consider assigning me this task, under GSSOC 2021.**

**Comment by rcoder23** [comment]
@neha-b2001 you can work on it . Add One Solution in One pull request .

**Comment by neha-b2001** [comment]
@rcoder23 I have made a PR for the Rabin-Karp algorithm (PR #174).
Since Rabin-Karp is an efficient way of string searching and already uses the concept of hashing, should I separately add a program for hashing, or just the Rabin-Karp program covers hashing as well?
